name: Deploy Web

on:
  push:
    tags: v*.*.*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Prepare
        run: |
          npm i
          npm run build.prod
        
      - name: Prepare archive
        run: |
          tar czf /tmp/explorer.tgz -C ./dist/blockexplorer/ .
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: explorer.tgz
          path: /tmp/explorer.tgz

  deploy:
    needs: build
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ web.1, web.2, web.3 ]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: explorer.tgz
      - name: Unpack artifact
        run: tar xzf explorer.tgz -C /data/expl/
      - name: Reset nginx cache
        run: /data/reset_cache.sh
