# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ disabled ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: gui

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Prepare
        run: |
          npm ci --only-production
          ng build --prod --base-href https://test.pocketnet.app/blockexplorer

      # Runs a set of commands using the runners shell
      - name: Deploy
        run: |
          rm -rf /docker/expl/*
          rsync -ah ./dist/blockexplorer/ /docker/expl/
